config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'home', to: 'pages#home'
  root to: 'pages#home'

  get 'rules', to: 'pages#rules'
  get 'schedule', to: 'pages#schedule'
  get 'enlightenment', to: 'pages#enlightenment'
  get 'calendar', to: 'pages#calendar'
  get 'contacts', to: 'pages#contacts'

  resources :clerics
  resources :announcements, except: [:index]
end

app/models/announcement.rb
class Announcement < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/cleric.rb
class Cleric < ApplicationRecord
  validates :name, presence: true
  validates :position, presence: true

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :check_if_admin, except: [:show]
  before_action :find_announcement, only: [:edit, :update, :delete, :destroy]

  def show
    @announcement = Announcement.last
  end

  def new
    @announcement = Announcement.new
  end

  def create
    @announcement = Announcement.create(announcement_params)
    @announcement.errors.empty? ? (redirect_to action: 'show', id: Announcement.last.id) : (render 'new')
  end

  def edit
  end

  def update
    if current_user.admin?
      @announcement.update(announcement_params)
      redirect_to @announcement if @announcement.errors.empty?
    else
      render file: "#{Rails.root}/public/403.html", status: 403, layout:false
    end
  end

  def delete
  end

  def destroy
    @announcement.destroy
    redirect_to root_path
  end

  private
    def check_if_admin
      render file: "#{Rails.root}/public/403.html", status: 403, layout: false unless current_user.admin == true
    end

    def find_announcement
      @announcement = Announcement.find(params[:id])
    end

    def announcement_params
      params.require(:announcement).permit(:title, :body)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/clerics_controller.rb
class ClericsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :check_if_admin, except: [:index, :show]
  before_action :find_cleric, only: [:show, :edit, :update, :delete, :destroy]

  def index
    @clerics = Cleric.all
  end

  def show
  end

  def new
    @cleric = Cleric.new
  end

  def create
    @cleric = Cleric.create(cleric_params)
    @cleric.errors.empty? ? (redirect_to clerics_path) : (render 'new')
  end

  def edit
  end

  def update
    if current_user.admin?
      @cleric.update(cleric_params)
      redirect_to @cleric if @cleric.errors.empty?
    else
      render file: "#{Rails.root}/public/403.html", status: 403, layout:false
    end
  end

  def delete
  end

  def destroy
    @cleric.destroy
    redirect_to clerics_path
  end

  private
    def check_if_admin
      render file: "#{Rails.root}/public/403.html", status: 403, layout: false unless current_user.admin == true
    end

    def find_cleric
      @cleric = Cleric.find(params[:id])
    end

    def cleric_params
      params.require(:cleric).permit(:name, :position, :image)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def rules
  end

  def schedule
  end

  def enlightenment
  end

  def calendar
  end

  def contacts
  end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clerics_helper.rb
module ClericsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/announcements/_form.html.erb
<%= simple_form_for @announcement do |f| %>
  <p>Заголовок: <br><%= f.input :title, label: false, input_html: { style: 'width: 100%'} %></p>
  <p>Новость: <br><%= f.cktext_area :body, label: false %></p>
  <%= f.submit "Create" %>
<% end %>

app/views/announcements/edit.html.erb
<h2>Редактировать</h2>
<%= render 'form' %>

app/views/announcements/new.html.erb
<h2>Создать</h2>
<%= render 'form' %>

app/views/announcements/show.html.erb
<div>
  <h2 class="announcement-title"><%= @announcement.title.html_safe %></h2><br>
  <span><%= @announcement.body.html_safe %></span><br>

  <% if current_user && current_user.admin? %>
    <%= link_to 'edit', edit_announcement_path(@announcement) %>
       <%= link_to 'delete', announcement_path(@announcement), method: :delete, data: { confirm: 'Уверены?' } %>
  <% end %>
</div>

app/views/clerics/_form.html.erb
<%= simple_form_for @cleric do |f| %>
  <p>Имя: <br><%= f.input :name, label: false %></p>
  <p>Должность: <br><%= f.input :position, label: false %></p>
  <p><%= f.input :image, label: false %></p>
  <%= f.submit "Create" %>
<% end %>

app/views/clerics/index.html.erb
<div id="clergy-page">
  <h1>Служители</h1>
  <ul class="grid">
    <% @clerics.each do |cleric| %>
      <li class="cleric-cart">
        <%= image_tag cleric.image.normal %>
        <span class="position"><%= cleric.position %></span>
        <span class="name"><%= cleric.name %></span>
      </li>
    <% end %>
  </ul>
</div>

app/views/clerics/show.html.erb
<div class="cleric-cart">
  <%= image_tag @cleric.image.normal %> <br>
  <span class="position"><%= @cleric.position %></span><br>
  <span class="name"><%= @cleric.name %></span><br>

  <% if current_user.admin? %>
    <%= link_to 'edit', edit_cleric_path(@cleric) %>
       <%= link_to 'delete', cleric_path(@cleric), method: :delete, data: { confirm: 'Уверены?' } %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Catedra</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <script src="https://use.fontawesome.com/0b7d5d47f3.js"></script>

  <body>
    <div id='header'>
      <div id="menu" onclick="toggleClass();">
        <span onclick="toggleClass();"><i class="fa fa-bars" aria-hidden="true" onclick="toggleClass();toggleIcon()" style="font-size:1.5em;color:white;padding-top:0.3em;"></i></span>
      </div>

      <header>
        <a href="/" class="home-link"><h2>Храм</h2></a>
      </header>
    </div>

    <div id='sidebar' onclick="toggleClass();toggleIcon()" >
        <nav role='navigation' id="nav" class="hidden" >
          <div className="menu-block">
            <ul>
              <li>
                <% sleep(0.5) %>
                <%= link_to "Расписание богослужений", schedule_path %>
              </li>

              <li>
                <%= link_to "Приходские объявления", announcement_path(Announcement.last) %>
              </li>

              <li>
                <%= link_to "Календарь Событий", calendar_path %>
              </li>

              <li>
                <%= link_to "Правила поведения", rules_path %>
              </li>

              <li>
                <%= link_to "Культура и образование", enlightenment_path %>
              </li>

              <li>
                <a href="#">Приход!</a>
              </li>

              <li>
                <%= link_to "Служители", clerics_path %>
              </li>

              <li>
                <a href="#">Галерея!</a>
              </li>

              <li>
                <%= link_to "Контакты", contacts_path %>
              </li>
            </ul>
            <div class="social-links">
              <a href="https://www.facebook.com/catedra.ru"><img src="assets/icons/facebook-logo-round-red.svg" alt="Fb" class="icons"></a>

              <a href="https://vk.com/catedra"><img src="assets/icons/vk-social-red.svg" alt="VK" class="icons"></a>

              <a href="https://ru.wikipedia.org/wiki/%D0%A1%D0%BE%D0%B1%D0%BE%D1%80_%D0%9D%D0%B5%D0%BF%D0%BE%D1%80%D0%BE%D1%87%D0%BD%D0%BE%D0%B3%D0%BE_%D0%97%D0%B0%D1%87%D0%B0%D1%82%D0%B8%D1%8F_%D0%9F%D1%80%D0%B5%D1%81%D0%B2%D1%8F%D1%82%D0%BE%D0%B9_%D0%94%D0%B5%D0%B2%D1%8B_%D0%9C%D0%B0%D1%80%D0%B8%D0%B8_(%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D0%B0)"><img src="assets/icons/wikipedia-logo-red.svg" alt="Wiki" class="icons"></a>
            </div>
          </div>
        </nav>
      </div>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/calendar.html.erb
<div>
  <h1>Календарь событий</h1>
  <div id="calendar-page">
    <iframe id='calendar' src="https://calendar.google.com/calendar/embed?height=600&amp;wkst=2&amp;bgcolor=%23ffffff&amp;src=acht97kleocgk125jl1fnibe7k%40group.calendar.google.com&amp;color=%238C500B&amp;ctz=Europe%2FMoscow">
    </iframe>
  </div>
</div>

app/views/pages/contacts.html.erb
<div id="contact-page">
  <div class="card-background">
    <div class="card">
      <p>
        123557 Москва <br/>
        улица Малая Грузинская 27/13 <br/>
        понедельник - воскресенье <br/>
        8:00 - 12:45 | 15:30 - 20:00
      </p>
      <a class="button" href="https://www.google.ru/maps/dir//Малая+Грузинская+ул.,+Москва/@55.7671279,37.5701984,17z/data=!3m1!4b1!4m5!3m4!1s0x46b54a2e59970acf:0xcd23fc08cbdceae7!8m2!3d55.767381!4d37.5721748?hl=ru" target="_blank">МАРШРУТ</a>
    </div>
  </div>

  <div id="main-contact">
    <div class="left">
      <p>
        <b>Ризница:</b> <a href="tel:+74992523911">+7(499)252-39-11</a><br/>
        <b>Концерты:</b> <a href="tel:+74992524051">+7(499)252-40-51</a><br/>
        <a href="mailto:catedra.moscow@gmail.com" target="_blank">catedra.moscow@gmail.com</a>
        <br/>
        <a href="https://www.facebook.com/catedra.ru">Группа в Facebook</a> <br/>
        <a href="https://vk.com/catedra" target="_blank">Группа в VK</a><br/>
        <a href="https://www.youtube.com/watch?v=7nbaiaLmwKE" target="_blank">Видео 'Как пройти к собору'</a>
      </p>

      <p>
        <b>Экскурсии</b><br/>
        Бесплатные экскурсии по кафедральному собору проводятся по предварительной записи по вторникам, средам и пятницам во время, свободное от богослужений. Организацию экскурсий осуществляет фонд <a href="http://deboniarte.org/">Искусство добра</a>.
      </p>

      <p>
        Посещение собора посторонними экскурсионными группами также осуществляется только по предварительному согласованию.
      </p>

      <p>
        Контакты: <br/>
        с. Наталия Кабишева<br/>
        <a href="tel:+74992524051">+7(499)252-40-51</a><br/>
        <a href="mailto:angelus@deboniarte.org">angelus@deboniarte.org </a>
      </p>
    </div>

    <div class="right">
      <p>
        <b>Журналистам</b><br/>
        По вопросам съемок и интервью в соборе обращайтесь
        к о. Кириллу Горбунову <br/>
        <a href="tel:+74957855434">+7(495)785-54-34</a> <br/>
        <a href="mailto:info@cathmos.ru">info@cathmos.ru</a>
        <br/>
      </p>

      <p><b>Ближайшие станции метро:</b><br/>
        <span>Баррикадная</span>,<br/>
        <span>Улица 1905  года</span>,<br/>
        <span>Краснопресненская</span>,<br/>
        <span>Белорусская</span>.
      </p>

      <h3>Реквизиты</h3>

      <p>РО – Приход Непорочного Зачатия Пресвятой Девы Марии Римско-Католической Церкви в г. Москве</p>
      <p>ИНН 7703126634 / КПП 770301001 <br/>
      р/с 40703810400060000001 <br/>
      кор/сч. 30101810145250000411 <br/>
      В Филиал «Центральный» Банка ВТБ (публичное акционерное общество) <br/> г. Москва / БИК 044525411
      </p>
    </div>
  </div>
</div>

app/views/pages/enlightenment.html.erb
<div class="regular-page">
  <h1>Культура и образование</h1>

  <section class="text-section">
    <h2>Музыка</h2>
    <p class="text-wrapper">
      <b>Литургическая музыка.</b> При соборе действует литургический приходской хор (занятия проходят по средам в 19.00 в хоровом классе в цокольном этаже), а также молодежная вокально-инструментальная группа.
      Приглашаем всех желающих.
    </p>

    <div class="image-wrapper">
      <%= image_tag "enlightenment/organ-2.jpg" %>
      <span class="sign"><i>Haarlem cathedral organ by muller. 1738 г.</i></span>
    </div>

    <p class="text-wrapper">
      <b>Концерты духовной музыки.</b> Дорогие прихожане!
      При соборе действует литургический приходской хор (занятия проходят по средам в 19.00 в хоровом классе в цокольном этаже), а также молодежная вокально-инструментальная группа.
      Приглашаем всех желающих.
      <br/>
      <br/>
      Мы часто слышим и размышляем над тем, что мы - христиане, мы - католики, мы – прихожане, мы  дети  Бога-Отца, мы являемся одной семьей. Все это значит, что мы ответственны за свое личное спасение и спасение людей, которых Бог поставил на нашем жизненном пути.
      <br/>
      <br/>
      Еще в  1999 году, во время освящения нашего собора,  архиепископ  Тадеуш  Кондрусевич сказал: «Этот храм станет  домом  молитвы,  и местом, где будет звучать прекрасная музыка для всех людей, ищущих Бога». И с тех пор здесь  проходят концерты духовной музыки, которые дали возможность очень многим людям узнать из официальных источников  о существовании нашего храма  в нашем  огромном городе. Даже  для многих из вас, концерты духовной музыки были тем  импульсом, который пробудил в сердце тоску по Богу, по  настоящей жизни во Христе. Кроме того, концерты приносят существенную и основную финансовую поддержку, направленную на поддержание жизнедеятельности нашего храма. Вместе со священниками мы должны заботиться о нашем прекрасном храме, куда мы приходим  каждое воскресенье.
      <br/>
      <br/>
      Концерты духовной музыки - это  прекрасная возможность  пригласить  ваших друзей, знакомых, сослуживцев посетить  наш собор. Пусть это станет вашей заботой,   чтобы храм наполнялся  новыми  людьми, которых Господь ждет в Святых Дарах. На протяжении более 10 лет, концерты духовной музыки, совместно с приходом  организует фонд  «Искусство добра», который возглавляет с. Валентина.  В фонде работает команда профессионалов, которые составляют программы духовной музыки, приглашают известных исполнителей, ведут образовательную и благотворительную работу, осуществляют   духовно-просветительскую миссию.
      <br/>
      <br/>
      Вы имеете возможность включиться в эту просветительскую, апостольскую миссию, приняв участие в распространении информации о нашем соборе, о нашем органе, о наших концертах. Вы можете получить информацию, материалы, узнать в каких проектах фонда вы можете поучаствовать.
      <br/>
      <br/>
      С вопросами и предложениями можно обращаться в офис фонда "Искусство добра" в Соборе. Из притвора - направо по лестнице на второй этаж.
      <br/>
      <br/>
      <b><a href="https://artbene.ru/">Афиша концертов</a></b>
    </p>
  </section>

  <section class="text-section">
    <h2>Образование</h2>
    <span><b>Английский язык с носителем!</b><br/></span>
    <span>Открыт набор в группу занятий английским языком с носителем<br/>
    Набираются дети от 3-х лет. </span>
      <br/>
      <ul>
        <li>Игровая форма</li>
        <li>Непринужденная атмосфера</li>
        <li>Естественный путь освоения языка</li>
        <li>Профессиональный преподаватель с опытом работы с детьми от 3-х лет</li>
      </ul>

      Контакты: <br/>
      Мария Логинова <br/>

      <a href="tel:+79296267880">+7(929)626-78-80</a><br/>
      <a href="mailto:">maria.loginova@mail.ru</a>
  </section>

  <section class="text-section">
    <h2>Экскурсии</h2>
    <p><b>Бесплатные </b>экскурсии по кафедральному собору проводятся по предварительной записи по вторникам, средам и пятницам во время, свободное от богослужений. Организацию экскурсий осуществляет фонд <a href="http://deboniarte.org/">Искусство добра</a>.
    </p>

    <p>
      Посещение собора посторонними экскурсионными группами также осуществляется только по предварительному согласованию.
    </p>

    Контакты: <br/>
    с. Наталия Кабишева <br/>

    <a href="tel:+74992524051">+7(499)252-40-51</a><br/>
    <a href="mailto:">angelus@deboniarte.org</a>
  </section>
</div>

app/views/pages/home.html.erb
<div class="regular-page">
  <h1>
    Собор Непорочного Зачатия<br/> Пресвятой Девы Марии
  </h1>

  <div class="text-section">
    <%= image_tag "home/sobor_draw.jpg", class: "horisontal-img-left" %>
    <p class="text-wrapper">
      Крупнейший католический собор в России, кафедральный собор архиепархии Матери Божией, возглавляемой архиепископом митрополитом Паоло Пецци. Третий по счёту московский католический храм, построенный до революции 1917 года, один из трёх действующих в настоящее время католических храмов Москвы наряду с храмом святого Людовика и храмом святой Ольги.

      Расположен по адресу: Малая Грузинская улица, дом 27/13. Ближайшие станции метро — Краснопресненская, Улица 1905 года и Белорусская-кольцевая.

      В соборе служат мессы на русском, польском, корейском, английском, французском, испанском языках, латыни, а также тридентские мессы и мессы по армянскому обряду. Кроме того, проводятся встречи молодёжи, курсы катехизации, благотворительные концерты органной, церковной и классической музыки. При соборе есть библиотека и церковная лавка, офис регионального отделения «Каритас» и благотворительный фонд «Искусство добра».
    </p>
  </div>
</div>

app/views/pages/rules.html.erb
<div class="regular-page">
  <h1>Правила поведения</h1>
  <h2>Общие правила:</h2>

  <ul>
    <li>
      Во всех помещениях собора мужчинам необходимо находиться без головных уборов, женщинам - в закрытой одежде, исключающей декольте, оголенные живот, колени и плечи.
    </li>
    <li>
      Отключайте звук ваших мобильных телефонов и других устройств! В случае необходимости разговоров по мобильному телефону просим выходить в притвор собора.
    </li>
    <li>
      Разговаривать в соборе можно не громче, чем вполголоса.
    </li>
    <li>
      Не разрешается прием пищи и напитков.
    </li>
    <li>
      Вход в собор в нетрезвом виде запрещен.
    </li>
    <li>
      Курение возможно только за оградой территории собора.
    </li>
    <li>
      Посетителям нельзя заходить в пресбитериум (возвышенная часть в конце главного нефа), где находятся Алтарь.
    </li>
    <li>
      В боковых нефах находятся деревянные сооружения — конфессионалы (исповедальни), в которых совершается таинство Исповеди. Не стоит подходить к ним близко или стоять около них долгое время.
    </li>
  </ul>


<h2>Во время Богослужения:</h2>

  <ul>
    <li>Желательно приходить на Мессу за 10-15  мин.</li>
    <li>Входя в храм, католики опускают правую руку в чашу со святой водой (находится в притворе справа и слева от входа), осеняют себя крестным знамением.</li>
    <li>
      Опоздав, помните служба уже идет, будьте внимательны,  чтобы не  помешать молитве других.
    </li>
    <li>
      Во время Богослужения нельзя вставать, ходить по храму, разговаривать, фотографировать, производить аудио- или видео съемку.
    </li>
    <li>
      Продолжительность Святой Мессы редко превышает час, поэтому желательно не покидать храм до ее завершения.
    </li>
    <li>
      Маленькие скамеечки внизу предназначены для того, чтобы на них становились на колени, поэтому желательно не опускать на них обувь.
    </li>
    <li>
      Во время сбора пожертвований к Вам, как и к любому чаловеку в храме могут подойти министранты (служащие) с корзиной для сбора пожертвований. Пожертвования являются абсолютно добровольными.
    </li>
    <li>
      Во время Причастия верующие встают и подходят к краю Пресбитериума (возвышенная часть в конце главного нефа). Подходить к Причастию может только    крещённый католик, не имеющий смертых грехов, бывший недавно на Исповеди.
    </li>
  </ul>

</div>